version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - SUPABASE_URL=${SUPABASE_URL:-https://your-project.supabase.co}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-your-anon-key}
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - redis

  # Scraper Service
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL:-https://your-project.supabase.co}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-your-anon-key}
    restart: unless-stopped
    networks:
      - app-network
    # Run demo scraper on startup, then sleep
    command: sh -c "node dist/demo-scraper.js && tail -f /dev/null"

  # Redis for session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge